# fly.toml file generated for the-adult-learner-hub on 2023-08-31T04:38:36Z

app = "the-adult-learner-hub"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "ord"
processes = []

[[services]]
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
