databases:
  - name: theadultlearner
    plan: free
    databaseName: theadultlearner
    user: theadultlearner

services:
  - type: web
    name: theadultlearner
    plan: free
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: theadultlearner
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
